### PR TITLE
Desktop integration improvements

### PR DESCRIPTION
**Pull request by trebmuh**
Hi, here you have a nekobee.desktop file which adds standard menu item and a nekobee.xpm which is used by the desktop to display a nice image in the menu. Hope it'll be useful.

Thanks for nekobee !

### CODE REVIEW

**Comment by trebmuh** [comment]
@gordonjcp ping

**Comment by trebmuh** [comment]
@gordonjcp : any issue with merging this one?

**Comment by trebmuh** [comment]
@gordonjcp ping

**Comment by gordonjcp** [comment]
I can merge that :-)  I'm not sure Nekobee even works on modern distros any more though...

**Comment by trebmuh** [comment]
thanks for merging :+1:

**Pull request merged**
